global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
rule_files:
  - 'alert.rules.yml'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_localhost'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['127.0.0.1:9115']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 127.0.0.1:9115
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
  - job_name: mysql
    static_configs:
      - targets:
        - 127.0.0.1:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9104
  - job_name: 'php-fpm_exporter'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['localhost:9145']
